language: python
python:
- '2.7'
- '3.7'
install:
- pip install 'pynag>=0.9.1'
- pip install unittest2==1.1.0
- pip install coveralls
- pip install paramiko
- pip install future
- python setup.py build
before_script:
- env
- git config --global user.email "noreply@travis-ci.org"
- git config --global user.name "Travis"
script:
- coverage run --source=okconfig tests/test.py
after_success:
- coveralls
deploy:
  provider: pypi
  user: gardart
  password:
    secure: Gs/t8tpslCAULwE5DozujxQ2/q+diDVGc6C/WYWcar97bYdL+E1xPb0xS8hsUIOkBO0oDalkYQoBl2P0TlGh33jtysrVYqrlEqMpdmvnmQO39DajjwRHNjOBlu9AlNy856VBg3oQK2EaYRjuBq3uC/A7Uv3lKOxCOxf0P14L5uU=
  on:
    tags: true
    branch: master
notifications:
  email: false
  irc:
    channels:
    - chat.freenode.net#okconfig
    on_failure: always
    on_success: change
