language: python
python:
  #- "2.6" # Python 2.6 is no longur supported in builds
  - "2.7"
install:
  - pip install 'pynag<=0.8.9'
  - pip install unittest2==0.5.1
  - pip install coveralls
  - pip install paramiko
  - python setup.py build
before_script:
  - env
  - git config --global user.email "noreply@travis-ci.org"
  - git config --global user.name "Travis"
script:
  - coverage run --source=okconfig tests/test.py
after_success:
  - coveralls
notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#okconfig"
    on_failure: always
    on_success: change

